spring:
  datasource:
    url: jdbc:mysql://localhost:3306/running_coach
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080

oauth:
  kakao:
    client-id: REDACTED_KAKAO_CLIENT_ID
    redirect-uri: http://localhost:5173/auth/kakao/callback
  # toss:
  #   client-id: YOUR_TOSS_CLIENT_ID
  #   client-secret: YOUR_TOSS_CLIENT_SECRET
  #   redirect-uri: http://localhost:5173/auth/toss/callback
  #   token-uri: https://oauth2.toss.im/token
  #   user-info-uri: https://oauth2.toss.im/me
